# Generated by Django 4.1.5 on 2023-01-10 23:30

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialwidget', '0002_userprofile_business_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 23, 30, 14, 975288)),
        ),
        migrations.AlterField(
            model_name='special',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
