# Generated by Django 4.1.5 on 2023-01-10 23:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialwidget', '0003_special_expires_alter_special_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=datetime.datetime(2023, 1, 10, 23, 37, 19, 499183))),
                ('send', models.BooleanField(default=True)),
                ('business_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Business Name')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('redirect_url', models.CharField(blank=True, help_text='This is where uses will be redirected after a call to action (e.g. Website for online ordering...)', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('twilio_from_sms', models.CharField(blank=True, max_length=100, null=True)),
                ('gmb_credentials', models.CharField(blank=True, max_length=12000, null=True)),
                ('gmb_access_token', models.CharField(blank=True, max_length=12000, null=True)),
                ('gmb_refresh_token', models.CharField(blank=True, max_length=12000, null=True)),
                ('gmb_accounts', models.CharField(blank=True, max_length=12000, null=True)),
                ('gmb_location', models.CharField(blank=True, max_length=12000, null=True)),
                ('gmb_location_name', models.CharField(blank=True, max_length=12000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 23, 37, 19, 498044)),
        ),
        migrations.AlterField(
            model_name='special',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
