# Generated by Django 4.1.5 on 2023-01-11 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialwidget', '0004_membership_alter_special_expires_alter_special_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='place_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 11, 19, 5, 37, 851721)),
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 19, 5, 37, 851082)),
        ),
    ]
