# Generated by Django 4.1.5 on 2023-01-12 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialwidget', '0005_membership_place_id_alter_membership_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 17, 27, 44, 256155)),
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 17, 27, 44, 255540)),
        ),
    ]
