# Generated by Django 4.1.5 on 2023-01-12 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialwidget', '0006_alter_membership_date_added_alter_special_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 12, 17, 31, 37, 947459)),
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 14, 17, 31, 37, 946826)),
        ),
        migrations.AlterField(
            model_name='special',
            name='image',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
