# Generated by Django 4.1.5 on 2023-01-15 21:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialwidget', '0007_alter_membership_date_added_alter_special_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='color',
            field=models.CharField(blank=True, default='F18805', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 21, 32, 49, 682850)),
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 21, 32, 49, 681825)),
        ),
    ]
