# Generated by Django 4.1.5 on 2023-01-15 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialwidget', '0008_special_color_alter_membership_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 21, 41, 59, 957605)),
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 21, 41, 59, 956809)),
        ),
    ]
