# Generated by Django 4.1.5 on 2023-01-15 21:50

import colorfield.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialwidget', '0009_special_active_alter_membership_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 21, 50, 56, 627151)),
        ),
        migrations.AlterField(
            model_name='special',
            name='color',
            field=colorfield.fields.ColorField(default='F18805', image_field=None, max_length=18, samples=None),
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 21, 50, 56, 625959)),
        ),
    ]
