# Generated by Django 4.1.5 on 2023-01-19 18:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialwidget', '0011_alter_membership_date_added_alter_special_expires_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 19, 18, 33, 44, 895059)),
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 21, 18, 33, 44, 894264)),
        ),
    ]
