# Generated by Django 4.1.5 on 2023-01-24 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialwidget', '0013_alter_membership_date_added_alter_special_expires_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='membership',
            field=models.ManyToManyField(to='specialwidget.membership'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 23, 4, 31, 99724)),
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 23, 4, 31, 101136)),
        ),
    ]
