# Generated by Django 4.1.5 on 2023-01-24 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialwidget', '0015_remove_membership_user_remove_special_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 23, 45, 38, 983777)),
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 23, 45, 38, 984987)),
        ),
    ]
