# Generated by Django 4.1.5 on 2023-01-24 23:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialwidget', '0016_alter_membership_date_added_alter_special_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 24, 23, 45, 56, 719720)),
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 23, 45, 56, 721227)),
        ),
    ]
