# Generated by Django 4.1.5 on 2023-01-25 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialwidget', '0017_alter_membership_date_added_alter_special_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 2, 13, 8, 221723)),
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 2, 13, 8, 223101)),
        ),
    ]
