# Generated by Django 4.1.5 on 2023-01-25 02:37

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('specialwidget', '0018_alter_membership_date_added_alter_special_expires'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='user_group',
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 2, 37, 58, 882449)),
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 27, 2, 37, 58, 885234)),
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
