# Generated by Django 4.1.5 on 2023-01-26 16:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specialwidget', '0019_remove_membership_user_group_membership_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='view',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 26, 16, 27, 17, 212103)),
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 16, 27, 17, 214207)),
        ),
        migrations.RemoveField(
            model_name='special',
            name='membership',
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=250)),
                ('signup_date', models.DateTimeField(auto_now=True)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specialwidget.membership')),
                ('special', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specialwidget.special')),
            ],
        ),
        migrations.AddField(
            model_name='special',
            name='membership',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='specialwidget.membership'),
        ),
    ]
