# Generated by Django 4.1.5 on 2023-01-28 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialwidget', '0020_special_view_alter_membership_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 28, 17, 42, 6, 969574)),
        ),
        migrations.AlterField(
            model_name='special',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 17, 42, 6, 971849)),
        ),
    ]
