# Generated by Django 5.2.4 on 2025-08-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_special_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='enable_email_signup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='special',
            name='order_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='special',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
