# Generated by Django 5.2.4 on 2025-08-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_special_enable_email_signup_special_order_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='cta_choices',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='special',
            name='mobile_order_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='special',
            name='description',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='special',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
