# Generated by Django 5.2.4 on 2025-08-04 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_special_cta_choices_special_mobile_order_url_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='user_profile',
            field=models.ForeignKey(blank=True, help_text='Owner of this special', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specials', to='profiles.userprofile'),
        ),
    ]
